---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Include lapce role
      ansible.builtin.include_role:
        name: "{{ ansible_role_name | default(lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename) }}"
