name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          args: ""
          setup_python: "true"
          working_directory: ""
          requirements_file: ""

  molecule:
    name: Molecule Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install molecule molecule-docker
      - name: Install required ansible collections
        run: |
          echo "Attempting to install ansible collections..."
          # Try multiple approaches to install collections
          if ansible-galaxy collection install -r requirements.yml; then
            echo "Successfully installed collections from requirements.yml"
          elif ansible-galaxy collection install community.docker ansible.posix; then
            echo "Successfully installed collections directly"
          else
            echo "Warning: Failed to install ansible collections. This may cause molecule tests to fail."
            echo "The collections community.docker and ansible.posix are required for Docker-based testing."
            exit 0  # Don't fail the job, let molecule tests handle the missing dependencies
          fi
        continue-on-error: true
      - name: Run molecule tests
        run: |
          echo "Running molecule tests..."
          if molecule test; then
            echo "Molecule tests completed successfully"
          else
            echo "Warning: Molecule tests failed. This may be due to missing ansible collections."
            echo "Please check that community.docker and ansible.posix collections are available."
            exit 1
          fi